"""Generates REPORT.md — readable portfolio summary visible on GitHub."""
import json
import os
from datetime import datetime

PORTFOLIO_FILE = "logs/portfolio.json"
REPORT_FILE = "REPORT.md"


def load_portfolio():
    if not os.path.exists(PORTFOLIO_FILE):
        return None
    with open(PORTFOLIO_FILE) as f:
        return json.load(f)


def main():
    p = load_portfolio()
    now = datetime.now().strftime("%Y-%m-%d %H:%M IST")

    lines = []
    lines.append("# 📈 Trading Bot — Live Portfolio Report")
    lines.append(f"\n**Last updated:** {now}\n")

    if not p:
        lines.append("No portfolio data yet.")
        with open(REPORT_FILE, "w") as f:
            f.write("\n".join(lines))
        return

    starting = 100000
    cash = p.get("cash", starting)
    positions = p.get("positions", {})
    trades = p.get("trades", [])

    # Estimate current value (use avg price as proxy since no live price here)
    position_value = sum(pos["qty"] * pos["avg_price"] for pos in positions.values())
    total = cash + position_value
    pnl = total - starting
    pnl_pct = (pnl / starting) * 100
    pnl_emoji = "🟢" if pnl >= 0 else "🔴"

    lines.append("## 💰 Summary")
    lines.append(f"| | |")
    lines.append(f"|---|---|")
    lines.append(f"| Starting Capital | ₹{starting:,.2f} |")
    lines.append(f"| Current Value | ₹{total:,.2f} |")
    lines.append(f"| Cash Available | ₹{cash:,.2f} |")
    lines.append(f"| Total P&L | {pnl_emoji} ₹{pnl:+,.2f} ({pnl_pct:+.2f}%) |")

    if positions:
        lines.append("\n## 📂 Open Positions")
        lines.append("| Stock | Qty | Avg Buy Price | Current Est. Value |")
        lines.append("|---|---|---|---|")
        for symbol, pos in positions.items():
            short = symbol.replace(".NS", "")
            val = pos["qty"] * pos["avg_price"]
            lines.append(f"| {short} | {pos['qty']} | ₹{pos['avg_price']:.2f} | ₹{val:,.2f} |")
    else:
        lines.append("\n## 📂 Open Positions\nNo open positions.")

    if trades:
        lines.append("\n## 📋 Recent Trades (Last 10)")
        lines.append("| Time | Action | Stock | Qty | Price | Total | P&L |")
        lines.append("|---|---|---|---|---|---|---|")
        for t in reversed(trades[-10:]):
            short = t["symbol"].replace(".NS", "")
            pnl_str = f"₹{t.get('pnl', 0):+.2f}" if "pnl" in t else "-"
            action_emoji = "🟢 BUY" if t["action"] == "BUY" else "🔴 SELL"
            lines.append(f"| {t['time'][:16]} | {action_emoji} | {short} | {t['qty']} | ₹{t['price']:.2f} | ₹{t['total']:,.2f} | {pnl_str} |")

    lines.append(f"\n---\n*Auto-generated by trading bot every 30 min on weekdays 9:15 AM – 3:30 PM IST*")

    with open(REPORT_FILE, "w") as f:
        f.write("\n".join(lines))

    print(f"Report written to {REPORT_FILE}")


if __name__ == "__main__":
    main()
